---
- name: setting up Amazon Linux 2 to use docker repository
  block:
    - name: check if Amazon docker repo is enable
      shell: "amazon-linux-extras list | grep docker"
      register: docker_hint
      changed_when: false

    - name: enable Amazon docker repo
      shell: "amazon-linux-extras enable docker"
      when:
        - docker_hint.stdout.find("enabled") == -1
  when: ansible_distribution_version == "2"

- name: change docker_package var for Amazon
  set_fact:
    docker_package: docker
